# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ChicagoRuby
email: organizers@chicagoruby.org
description: >
  ChicagoRuby is a group of developers & designers who use Ruby, Rails,
  and related tech.
baseurl: ""
url: "https://chicagoruby.org"
medium_username:   chicagoruby
facebook_username: chicagoruby
twitter_username:  chicagoruby
vimeo_username:    chicagoruby
github_username:   chicagoruby

# Build settings
markdown: kramdown

collections:
  videos:
    output: true
    permalink: /videos/:path/

defaults:
  - scope:
      path: ""
      type: videos
    values:
      name:
      vimeo_id:
      event: "ChicagoRuby: Downtown"
      teaser:
      speaker:
      speaker_bio:
  -
    scope:
      path: "pages/advanced"
    values:
      layout: "page-advanced"
  -
    scope:
      path: "pages/simple"
    values:
      layout: "page-simple"
  -
    scope:
      path: "redirects"
    values:
      layout: "redirect"
  - scope:
      path: ""
      type: videos
    values:
      layout: video
