---
title: ChicagoRuby
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: true
    permalink: "/videos/:year/:month/:day/:title/"
defaults:
- scope:
    path: ''
    type: videos
  values:
    title:
    vimeo_id:
    youtube_id:
    event: 'ChicagoRuby: Downtown'
    teaser:
    speaker:
    speaker_bio:
- scope:
    path: pages/advanced
  values:
    layout: page-advanced
- scope:
    path: pages/simple
  values:
    layout: page-simple
- scope:
    path: redirects
  values:
    layout: redirect
- scope:
    path: ''
    type: videos
  values:
    layout: video
email: organizers@chicagoruby.org
description: |
  ChicagoRuby is a group of developers & designers who use Ruby, Rails, and related tech.
baseurl:
url: https://chicagoruby.org
medium_username: '@chicagoruby'
facebook_username: chicagoruby
twitter_username: chicagoruby
vimeo_username: chicagoruby
github_username: chicagoruby
markdown: kramdown
